version: '3.9'

services:
  ui:
    container_name: mytime-ui
    image: mytime-ui
    depends_on:
      - "api"
    environment:
      - CHOKIDAR_USEPOLLING=true # This allows CRA to hot reload over the file system barrier
      - BROWSER=none
      - NODE_ENV=development
    build:
      context: ./src/timesheet-app/.
      dockerfile: DOCKERFILE
      target: development
    volumes:
      - ./src/timesheet-app:/app
    ports:
      - 3000:3000

  sqlserver:
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "MyPass@word"
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    volumes:
      - "sql-server-data:/var/opt/mssql"
  
  api:
    container_name: mytime-api
    image: mytime-api
    depends_on:
      - "sqlserver"
    build:
      context: .
      dockerfile: ./src/MyTime.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings:MyTimeSqlDbContextConnectionString: "Data Source=sqlserver;Initial Catalog=mytime_app_dev;User Id=sa;Password=MyPass@word;Encrypt=false"
    ports:
      - "5000:5000"
      - "5001:5001"


volumes:
  sql-server-data:
