FROM node:14-alpine as development
ENV NODE_ENV development

WORKDIR /app

COPY ./package.json .package.json 
COPY ./yarn.lock .yarn.lock
RUN yarn install --frozen-lockfile
COPY . ./

EXPOSE 3000

CMD ["yarn", "start"]